version: '3.7'
services:
  db:
    image: postgres:12
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  frontend:
    build:
      context: ./frontend
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - './frontend:/app'
    command: /bin/sh -c "yarn install && yarn serve"
  backend:
    build:
      context: ./backend
      target: 'develop-stage'
    ports:
      - "8088:8088"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: /bin/sh -c "cargo watch -x run"
  nginx:
    image: nginx:1.17.10-alpine
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  db_data:
  cargo-cache:
  target-cache:
